# Generated by Django 4.0 on 2022-02-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20)),
                ('cin', models.BigIntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('dateNaissance', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.BigIntegerField()),
                ('etatCivile', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=500)),
            ],
        ),
    ]
