# Generated by Django 4.0 on 2022-02-23 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='branche',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nom', models.TextField(blank=True, null=True)),
                ('adress', models.TextField(blank=True)),
                ('pays', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('telephone', models.BigIntegerField(blank=True)),
                ('fax', models.BigIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='contract',
            fields=[
                ('contractID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('contactType', models.TextField(null=True)),
                ('dateDebut', models.DateField(null=True)),
                ('dateFin', models.DateField(null=True)),
                ('contactFile', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='diplome',
            fields=[
                ('diplomeID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('titreDiplome', models.TextField(null=True)),
                ('fileDiplome', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='formation',
            fields=[
                ('formationID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('titreformation', models.TextField(null=True)),
                ('fileFormation', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='responsable',
            fields=[
                ('matricule', models.CharField(blank=True, max_length=20)),
                ('cin', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('dateNaissance', models.DateField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.BigIntegerField(blank=True)),
                ('etatCivile', models.CharField(blank=True, max_length=50)),
                ('username', models.CharField(max_length=500)),
                ('password', models.TextField(blank=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmaoBaseApp.branche')),
                ('contract', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmaoBaseApp.contract')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='technicine',
            fields=[
                ('matricule', models.CharField(blank=True, max_length=20)),
                ('cin', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('dateNaissance', models.DateField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.BigIntegerField(blank=True)),
                ('etatCivile', models.CharField(blank=True, max_length=50)),
                ('username', models.CharField(max_length=200)),
                ('password', models.TextField(blank=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmaoBaseApp.branche')),
                ('contract', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmaoBaseApp.contract')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='formation',
            name='technicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmaoBaseApp.technicine'),
        ),
        migrations.AddField(
            model_name='diplome',
            name='technicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmaoBaseApp.technicine'),
        ),
    ]
