# Generated by Django 4.0 on 2022-02-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0002_branche_contract_diplome_formation_responsable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200)),
                ('prenom', models.CharField(blank=True, max_length=200)),
                ('login', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
