# Generated by Django 4.0 on 2022-02-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0004_branche_pdg'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technicine',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
