# Generated by Django 4.0 on 2022-03-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0005_responsable_isdeleted_technicine_isdeleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(blank=True, max_length=200)),
                ('profile', models.CharField(blank=True, max_length=200)),
                ('token', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
