# Generated by Django 4.0 on 2022-03-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0007_alter_tokens_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='token',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
