# Generated by Django 4.0 on 2022-03-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0008_alter_tokens_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tokens',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contactFile',
        ),
        migrations.AddField(
            model_name='contract',
            name='contact',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='technicine',
            name='isResponsableMaintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technicine',
            name='isResponsableProduction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technicine',
            name='suppheurePrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='fileDiplome',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='formation',
            name='fileFormation',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
