# Generated by Django 4.0 on 2022-03-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0009_delete_tokens_remove_contract_contactfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='technicine',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='technicine',
            name='contract',
        ),
        migrations.DeleteModel(
            name='diplome',
        ),
        migrations.DeleteModel(
            name='formation',
        ),
    ]
