# Generated by Django 4.0 on 2022-03-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0010_remove_formation_technicine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='cin',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='technicine',
            name='cin',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
