# Generated by Django 4.0 on 2022-03-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0011_alter_responsable_cin_alter_technicine_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='username',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
