# Generated by Django 4.0 on 2022-03-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0012_alter_responsable_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicine',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
