# Generated by Django 4.0 on 2022-03-24 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0013_alter_technicine_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('idAtelier', models.AutoField(primary_key=True, serialize=False)),
                ('nomAtelier', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='technicine',
            name='atelier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmaoBaseApp.atelier'),
        ),
    ]
