# Generated by Django 4.0 on 2022-03-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0014_atelier_technicine_atelier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contract',
        ),
    ]
