# Generated by Django 4.0 on 2022-03-29 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0015_delete_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsable',
            old_name='username',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='responsable',
            old_name='password',
            new_name='motDePasse',
        ),
        migrations.RenameField(
            model_name='technicine',
            old_name='username',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='technicine',
            old_name='password',
            new_name='motDePasse',
        ),
    ]
