# Generated by Django 4.0 on 2022-03-29 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0016_rename_username_responsable_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsable',
            name='dateNaissance',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='email',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='etatCivile',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='isDeleted',
        ),
        migrations.RemoveField(
            model_name='technicine',
            name='dateNaissance',
        ),
        migrations.RemoveField(
            model_name='technicine',
            name='email',
        ),
        migrations.RemoveField(
            model_name='technicine',
            name='etatCivile',
        ),
        migrations.RemoveField(
            model_name='technicine',
            name='isDeleted',
        ),
    ]
