# Generated by Django 4.0 on 2022-03-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0017_remove_responsable_datenaissance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsable',
            name='cin',
        ),
        migrations.RemoveField(
            model_name='technicine',
            name='cin',
        ),
        migrations.AlterField(
            model_name='responsable',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='technicine',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
