# Generated by Django 4.0 on 2022-03-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0018_remove_responsable_cin_remove_technicine_cin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdg',
            old_name='password',
            new_name='moDePasse',
        ),
    ]
