# Generated by Django 4.0 on 2022-03-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0019_rename_password_pdg_modepasse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdg',
            old_name='moDePasse',
            new_name='motDePasse',
        ),
    ]
