# Generated by Django 4.0 on 2022-04-03 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0020_rename_modepasse_pdg_motdepasse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesMachines',
            fields=[
                ('codeCategorie', models.TextField(primary_key=True, serialize=False)),
                ('nomCategrie', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('brand', models.TextField()),
                ('model', models.TextField()),
                ('anneeManifacture', models.DateField()),
                ('currnetState', models.TextField(blank=True)),
                ('schudledTiem', models.IntegerField()),
                ('timeLosses', models.IntegerField()),
                ('descriptions', models.TextField(blank=True)),
                ('availibilty', models.IntegerField()),
                ('image', models.FileField(default='', upload_to='')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmaoBaseApp.categoriesmachines')),
            ],
        ),
    ]
