# Generated by Django 4.0 on 2022-04-12 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0021_categoriesmachines_machines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machines',
            old_name='schudledTiem',
            new_name='schudledTime',
        ),
        migrations.AddField(
            model_name='machines',
            name='atelier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gmaoBaseApp.atelier'),
        ),
    ]
