# Generated by Django 4.0 on 2022-04-24 00:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0025_alter_machines_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoriePreventif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomAction', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='cout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeDeCout', models.TextField(blank=True)),
                ('cout', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField(blank=True)),
                ('quantite', models.PositiveBigIntegerField(blank=True)),
                ('prix', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='sousTraitence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sousTraitence', models.TextField(blank=True)),
                ('nomRep', models.TextField(blank=True)),
                ('adress', models.TextField(blank=True)),
                ('telephone', models.BigIntegerField(blank=True)),
                ('fax', models.BigIntegerField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='branche',
            name='pdg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gmaoBaseApp.pdg'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='branche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gmaoBaseApp.branche'),
        ),
        migrations.AlterField(
            model_name='technicine',
            name='atelier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gmaoBaseApp.atelier'),
        ),
        migrations.AlterField(
            model_name='technicine',
            name='branche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gmaoBaseApp.branche'),
        ),
        migrations.CreateModel(
            name='pieceDeRechange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPiece', models.TextField(blank=True)),
                ('quantite', models.BigIntegerField(blank=True)),
                ('prixTotale', models.FloatField(blank=True)),
                ('cout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='gmaoBaseApp.cout')),
                ('detailDePiece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='gmaoBaseApp.magasin')),
            ],
        ),
        migrations.CreateModel(
            name='InterventionPreventive',
            fields=[
                ('codePreventif', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('Initials', models.TextField(blank=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gmaoBaseApp.machines')),
                ('planIntervention', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gmaoBaseApp.categoriepreventif')),
                ('technicine', models.ManyToManyField(to='gmaoBaseApp.technicine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntervenctionCurative',
            fields=[
                ('codeCuratif', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('dateRapport', models.DateTimeField()),
                ('sympthomes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('dateDebutAction', models.DateTimeField(blank=True)),
                ('diagnostique', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('dateFinAction', models.DateTimeField(blank=True)),
                ('dateCloture', models.DateTimeField(blank=True)),
                ('typeDePann', models.TextField(blank=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gmaoBaseApp.machines')),
                ('sousTraitence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gmaoBaseApp.soustraitence')),
                ('technicine', models.ManyToManyField(to='gmaoBaseApp.technicine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cout',
            name='Curative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gmaoBaseApp.intervenctioncurative'),
        ),
        migrations.AddField(
            model_name='cout',
            name='Prevetive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gmaoBaseApp.interventionpreventive'),
        ),
    ]
