# Generated by Django 4.0 on 2022-04-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0027_rename_typedepann_intervenctioncurative_typedepanne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervenctioncurative',
            name='etatInterventions',
            field=models.TextField(blank=True),
        ),
    ]
