# Generated by Django 4.0 on 2022-04-27 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0028_intervenctioncurative_etatinterventions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervenctioncurative',
            name='technicine',
        ),
        migrations.AddField(
            model_name='intervenctioncurative',
            name='technicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='gmaoBaseApp.technicine'),
        ),
        migrations.RemoveField(
            model_name='interventionpreventive',
            name='technicine',
        ),
        migrations.AddField(
            model_name='interventionpreventive',
            name='technicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='gmaoBaseApp.technicine'),
        ),
    ]
