# Generated by Django 4.0 on 2022-05-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0029_remove_intervenctioncurative_technicine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervenctioncurative',
            name='diagnostique',
            field=models.TextField(blank=True),
        ),
    ]
