# Generated by Django 4.0 on 2022-05-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0030_alter_intervenctioncurative_diagnostique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervenctioncurative',
            name='diagnostique',
            field=models.TextField(blank=True, null=True),
        ),
    ]
