# Generated by Django 4.0 on 2022-05-04 11:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0031_alter_intervenctioncurative_diagnostique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervenctioncurative',
            name='typeDePanne',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None),
        ),
    ]
