# Generated by Django 4.0 on 2022-05-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0032_alter_intervenctioncurative_typedepanne'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervenctioncurative',
            old_name='sympthomes',
            new_name='Sympthomes',
        ),
        migrations.RenameField(
            model_name='intervenctioncurative',
            old_name='typeDePanne',
            new_name='TypeDePanne',
        ),
    ]
