# Generated by Django 4.0 on 2022-05-11 09:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0033_rename_sympthomes_intervenctioncurative_sympthomes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervenctioncurative',
            name='TypeDePanne',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, size=None),
        ),
    ]
