# Generated by Django 4.0 on 2022-05-11 09:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0034_alter_intervenctioncurative_typedepanne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervenctioncurative',
            name='Sympthomes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, size=None),
        ),
    ]
