# Generated by Django 4.0 on 2022-05-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0035_alter_intervenctioncurative_sympthomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervenctioncurative',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmaoBaseApp.machines'),
        ),
        migrations.AlterField(
            model_name='interventionpreventive',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmaoBaseApp.machines'),
        ),
    ]
