# Generated by Django 4.0 on 2022-05-22 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0036_alter_intervenctioncurative_machine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervenctioncurative',
            name='technicine',
        ),
        migrations.RemoveField(
            model_name='interventionpreventive',
            name='technicine',
        ),
        migrations.AddField(
            model_name='intervenctioncurative',
            name='technicines',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gmaoBaseApp.technicine'),
        ),
        migrations.AddField(
            model_name='interventionpreventive',
            name='technicines',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gmaoBaseApp.technicine'),
        ),
        migrations.AlterField(
            model_name='branche',
            name='pdg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmaoBaseApp.pdg'),
        ),
        migrations.AlterField(
            model_name='piecederechange',
            name='cout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gmaoBaseApp.cout'),
        ),
        migrations.AlterField(
            model_name='piecederechange',
            name='detailDePiece',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gmaoBaseApp.magasin'),
        ),
        migrations.AlterField(
            model_name='technicine',
            name='atelier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gmaoBaseApp.atelier'),
        ),
    ]
