# Generated by Django 4.0 on 2022-05-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0037_remove_intervenctioncurative_technicine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervenctioncurative',
            name='technicines',
        ),
        migrations.AddField(
            model_name='intervenctioncurative',
            name='technicines',
            field=models.ManyToManyField(to='gmaoBaseApp.technicine'),
        ),
        migrations.RemoveField(
            model_name='interventionpreventive',
            name='technicines',
        ),
        migrations.AddField(
            model_name='interventionpreventive',
            name='technicines',
            field=models.ManyToManyField(to='gmaoBaseApp.technicine'),
        ),
    ]
