# Generated by Django 4.0 on 2022-05-22 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0038_remove_intervenctioncurative_technicines_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervenctioncurative',
            name='technicines',
        ),
        migrations.AddField(
            model_name='intervenctioncurative',
            name='technicines',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gmaoBaseApp.technicine'),
        ),
        migrations.RemoveField(
            model_name='interventionpreventive',
            name='technicines',
        ),
        migrations.AddField(
            model_name='interventionpreventive',
            name='technicines',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gmaoBaseApp.technicine'),
        ),
    ]
