# Generated by Django 4.0 on 2022-05-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0040_remove_intervenctioncurative_technicines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervenctioncurative',
            name='technicines',
            field=models.ManyToManyField(blank=True, to='gmaoBaseApp.technicine'),
        ),
        migrations.AlterField(
            model_name='interventionpreventive',
            name='technicines',
            field=models.ManyToManyField(blank=True, to='gmaoBaseApp.technicine'),
        ),
    ]
