# Generated by Django 4.0 on 2022-05-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0041_alter_intervenctioncurative_technicines_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interventionpreventive',
            name='Initials',
        ),
        migrations.AddField(
            model_name='categoriepreventif',
            name='DurationToRepeat',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interventionpreventive',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
