# Generated by Django 4.0 on 2022-05-22 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0042_remove_interventionpreventive_initials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piecederechange',
            name='cout',
        ),
        migrations.RemoveField(
            model_name='piecederechange',
            name='detailDePiece',
        ),
        migrations.AddField(
            model_name='piecederechange',
            name='Curative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gmaoBaseApp.intervenctioncurative'),
        ),
        migrations.AddField(
            model_name='piecederechange',
            name='Prevetive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gmaoBaseApp.interventionpreventive'),
        ),
        migrations.DeleteModel(
            name='magasin',
        ),
    ]
