# Generated by Django 4.0 on 2022-05-22 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0043_remove_piecederechange_cout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cout',
            old_name='cout',
            new_name='Cout',
        ),
    ]
