# Generated by Django 4.0 on 2022-05-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0044_rename_cout_cout_cout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piecederechange',
            old_name='prixTotale',
            new_name='PrixUnitaire',
        ),
    ]
