# Generated by Django 4.0 on 2022-05-23 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0047_categoriepreventif_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interventionpreventive',
            name='planIntervention',
        ),
        migrations.AddField(
            model_name='interventionpreventive',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interventionpreventive',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gmaoBaseApp.machines'),
        ),
        migrations.DeleteModel(
            name='categoriePreventif',
        ),
    ]
