# Generated by Django 4.0 on 2022-05-23 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0049_alter_intervenctioncurative_machine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervenctioncurative',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gmaoBaseApp.machines'),
        ),
        migrations.AlterField(
            model_name='intervenctioncurative',
            name='technicines',
            field=models.ManyToManyField(blank=True, default=[], to='gmaoBaseApp.technicine'),
        ),
        migrations.AlterField(
            model_name='interventionpreventive',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='gmaoBaseApp.machines'),
        ),
        migrations.AlterField(
            model_name='interventionpreventive',
            name='technicines',
            field=models.ManyToManyField(blank=True, default=[], to='gmaoBaseApp.technicine'),
        ),
    ]
