# Generated by Django 4.0 on 2022-05-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0050_alter_intervenctioncurative_machine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionpreventive',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
