# Generated by Django 4.0 on 2022-05-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaoBaseApp', '0051_alter_interventionpreventive_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecederechange',
            name='quantite',
            field=models.IntegerField(blank=True),
        ),
    ]
